### ISSUE TITLE
Cannot open "Developer options" on AOSP13 Android Automotive

### ISSUE THREAD

**Issue by RobinHeart317** [raspberry-vanilla/android_local_manifest#55]
Hi KonstaT,

Thank you for your work. It is wonderful. I have followed the file "Readme" in branch android-13.0 and built successfully. But I met an issue that I could not open "Developer Options" in Setting > System > Developer Options. Did I do anything wrong or did I miss something or even forgot to config something before build?

**Comment by KonstaT** [comment]
On `userdebug`/`user` builds you need to click Settings -> About tablet -> Build number several times to enable developer options (vs. `eng` builds where this is enabled by default).

**Comment by RobinHeart317** [comment]
I have enabled developer options but the problem is when I click on it it takes me back to settings. Please see the attached video below. 

https://drive.google.com/file/d/1wqw_5vyVIypDQcS_M0O8tSnDaY7yXgJG/view?usp=sharing

**Comment by KonstaT** [comment]
`logcat`?

Assuming this is `android-13.0` branch, Android Automotive build target, on Raspberry Pi 4. Can't recall experiencing similar issue, though.

**Comment by KonstaT** [comment]
Something like https://github.com/LineageOS/android_packages_modules_adb/commit/88411b79d13147583fcd96d2e8c94e6cc6839ee0 would help?

**Comment by remarkked** [comment]
> Something like [LineageOS/android_packages_modules_adb@88411b7](https://github.com/LineageOS/android_packages_modules_adb/commit/88411b79d13147583fcd96d2e8c94e6cc6839ee0) would help?

Missing root folder in packages/modules/adb. Pulling adb module branch to this commit causes many build failures:

**Comment by remarkked** [comment]
> Assuming this is `android-13.0` branch, Android Automotive build target, on Raspberry Pi 4. Can't recall experiencing similar issue, though.

Do Developer Options open normally on your build (android-13.0.0_r75 branch)?

Update: this fix was for LineageOS 21 (Android 14). Pulled last LineageOS 20 adb commit and manually inserted this fix in code, AOSP builds successfully, but fix doesn't work. Same behavior like @RobinHeart317 has.

P.S. Found this issue on IssueTracker (no solution): [https://issuetracker.google.com/319094599](https://issuetracker.google.com/319094599)

Logcat:
```
02-05 12:01:43.191   469   484 I ActivityTaskManager: START u10 {act=android.settings.APPLICATION_DEVELOPMENT_SETTINGS cmp=com.android.car.developeroptions/.CarDevelopmentSettingsDashboardActivity} from uid 1001000
02-05 12:01:43.196   469   484 E CellBroadcastUtils: getDefaultCellBroadcastReceiverPackageName: no package found
02-05 12:01:43.201   469   484 V SplashScreenExceptionList: SplashScreen checking exception for package com.android.car.developeroptions (target sdk:33) -> false
02-05 12:01:43.201   469   484 D CompatibilityChangeReporter: Compat change id reported: 205907456; UID 1001000; state: ENABLED
02-05 12:01:43.204   469   484 W WindowManager: lockNow pending, ignore updating lockscreen timeout
02-05 12:01:43.207   469   490 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 1001000; state: DISABLED
02-05 12:01:43.209   469   490 D CompatibilityChangeReporter: Compat change id reported: 177438394; UID 1001000; state: DISABLED
02-05 12:01:43.210  2036  2080 D SplashScreenView: Build android.window.SplashScreenView{ce9372d V.E...... ......ID 0,0-0,0}
02-05 12:01:43.210  2036  2080 D SplashScreenView: Icon: view: null drawable: null size: 0
02-05 12:01:43.210  2036  2080 D SplashScreenView: Branding: view: android.view.View{7ea6462 G.ED..... ......I. 0,0-0,0 #10204dc android:id/splashscreen_branding_view} drawable: null size w: 0 h: 0
02-05 12:01:43.210  2036  2075 W Parcel  : Expecting binder but got null!
02-05 12:01:43.210   469   490 D CompatibilityChangeReporter: Compat change id reported: 135772972; UID 1001000; state: DISABLED
02-05 12:01:43.211   469   490 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 1001000; state: ENABLED
02-05 12:01:43.214   254   254 W Zygote  : forkRepeatedly terminated due to non-simple command
02-05 12:01:43.214   254   254 D Zygote  : mbuffer starts with 17, nice name is , mEnd = 1668, mNext = 35, mLinesLeft = 15, mFd = 5
02-05 12:01:43.223   254   254 I Zygote  : Entering forkRepeatedly native zygote loop
02-05 12:01:43.224   469   893 W WindowManager: lockNow pending, ignore updating lockscreen timeout
02-05 12:01:43.232  2036  2075 E OpenGLRenderer: Unable to match the desired swap behavior.
02-05 12:01:43.241   469   484 W WindowManager: lockNow pending, ignore updating lockscreen timeout
02-05 12:01:43.246   469   490 D OomAdjuster: Not killing cached processes
02-05 12:01:43.247  1003  1003 D CarPackageManagerService: onWindowChange event received
02-05 12:01:43.248   254   254 D Zygote  : Forked child process 3666
02-05 12:01:43.255   469   497 I ActivityManager: Start proc 3666:com.android.car.developeroptions/u10s1000 for next-top-activity {com.android.car.developeroptions/com.android.car.developeroptions.CarDevelopmentSettingsDashboardActivity}
02-05 12:01:43.263  3666  3666 I Zygote  : seccomp disabled by setenforce 0
02-05 12:01:43.266   469   491 W WindowManager: lockNow pending, ignore updating lockscreen timeout
02-05 12:01:43.289  1384  1384 D FocusParkingView: The window of Activity [com.android.car.settings.common.SubSettingsActivity@d1f6304] lost focus
02-05 12:01:43.289  1384  1384 D FocusAreaHelper: The window of Activity [com.android.car.settings.common.SubSettingsActivity@d1f6304] lost focus
02-05 12:01:43.289  1384  1384 D FocusParkingView: The window of Activity [com.android.car.settings.common.SubSettingsActivity@d1f6304] lost focus
02-05 12:01:43.289  1384  1384 D FocusAreaHelper: The window of Activity [com.android.car.settings.common.SubSettingsActivity@d1f6304] lost focus
02-05 12:01:43.290  1384  1384 D FocusAreaHelper: The window of Activity [com.android.car.settings.common.SubSettingsActivity@d1f6304] lost focus
02-05 12:01:43.293  3635  3640 I adbd    : jdwp connection from 3666
02-05 12:01:43.303   469   549 D InputDispatcher: No new touched window at (465, 709) in display 0
02-05 12:01:43.303   469   549 I InputDispatcher: Dropping event because there is no touchable window at (465, 709) on display 0.
02-05 12:01:43.310   469   484 D CompatibilityChangeReporter: Compat change id reported: 184838306; UID 1001000; state: DISABLED
02-05 12:01:43.311   469   484 D CompatibilityChangeReporter: Compat change id reported: 185004937; UID 1001000; state: DISABLED
02-05 12:01:43.311   469   484 D CompatibilityChangeReporter: Compat change id reported: 181136395; UID 1001000; state: DISABLED
02-05 12:01:43.311   469   484 D CompatibilityChangeReporter: Compat change id reported: 174042936; UID 1001000; state: DISABLED
02-05 12:01:43.321  1003  1042 I CAR.AM  : onForegroundActivitiesChanged uid 1001000 pid 3666 fg true
02-05 12:01:43.324   469   491 W WindowManager: lockNow pending, ignore updating lockscreen timeout
02-05 12:01:43.326  3666  3666 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 1001000; state: ENABLED
02-05 12:01:43.333   469   484 W WindowManager: lockNow pending, ignore updating lockscreen timeout
02-05 12:01:43.342  2036  2075 E OpenGLRenderer: Unable to match the desired swap behavior.
02-05 12:01:43.368   469   491 W WindowManager: lockNow pending, ignore updating lockscreen timeout
02-05 12:01:43.376   469   491 W WindowManager: lockNow pending, ignore updating lockscreen timeout
02-05 12:01:43.383   469   549 D InputDispatcher: No new touched window at (466, 709) in display 0
02-05 12:01:43.383   469   549 I InputDispatcher: Dropping event because there is no touchable window at (466, 709) on display 0.
02-05 12:01:43.399   469   549 D InputDispatcher: No new touched window at (467, 709) in display 0
02-05 12:01:43.399   469   549 I InputDispatcher: Dropping event because there is no touchable window at (467, 709) on display 0.
02-05 12:01:43.404   469  3387 W Parcel  : Expecting binder but got null!
02-05 12:01:43.431   469   549 D InputDispatcher: No new touched window at (468, 708) in display 0
02-05 12:01:43.431   469   549 I InputDispatcher: Dropping event because there is no touchable window at (468, 708) on display 0.
02-05 12:01:43.449  3666  3666 V GraphicsEnvironment: ANGLE Developer option for 'com.android.car.developeroptions' set to: 'default'
02-05 12:01:43.450  3666  3666 V GraphicsEnvironment: ANGLE GameManagerService for com.android.car.developeroptions: false
02-05 12:01:43.451  3666  3666 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
02-05 12:01:43.455  3666  3666 D NetworkSecurityConfig: No Network Security Config specified, using platform default
02-05 12:01:43.456  3666  3666 D NetworkSecurityConfig: No Network Security Config specified, using platform default
02-05 12:01:43.459   469  3387 W Parcel  : Expecting binder but got null!
02-05 12:01:43.475  3666  3685 I carui   : CarUi plugin is disabled
02-05 12:01:43.524  3666  3666 D ActivityEmbeddingUtils: isFlagEnabled = true
02-05 12:01:43.524  3666  3666 D ActivityEmbeddingUtils: isSplitSupported = true
02-05 12:01:43.568  3666  3666 D ActivityEmbeddingUtils: isFlagEnabled = true
02-05 12:01:43.568  3666  3666 D ActivityEmbeddingUtils: isSplitSupported = true
02-05 12:01:43.574  3666  3666 I CarUiInstaller: CarUiInstaller started for com.android.car.developeroptions/.CarDevelopmentSettingsDashboardActivity
02-05 12:01:43.609  3666  3666 D CompatibilityChangeReporter: Compat change id reported: 210923482; UID 1001000; state: ENABLED
02-05 12:01:43.634  3666  3666 I CarUxRManager: Context returns display ID 0
02-05 12:01:43.654  3666  3666 D SettingsActivity: Starting onCreate
02-05 12:01:43.679  3666  3666 D SettingsActivity: Starting to set activity title
02-05 12:01:43.679  3666  3666 D SettingsActivity: Done setting title
02-05 12:01:43.680  3666  3666 D SettingsActivity: Switching to fragment com.android.car.developeroptions.CarDevelopmentSettingsDashboardFragment
02-05 12:01:43.682  3666  3666 D CompatibilityChangeReporter: Compat change id reported: 183155436; UID 1001000; state: ENABLED
02-05 12:01:43.700  3666  3666 W OemUnlockPreferenceController: oem_unlock not supported.
02-05 12:01:43.706  3666  3666 D ForcePeakRefreshRateCtr: DEFAULT_REFRESH_RATE : 60.0 mPeakRefreshRate : 60.0
02-05 12:01:43.749  3666  3666 D PrefCtrlListHelper: Could not find Context-only controller for pref: com.android.settings.notification.ImportanceResetPreferenceController
02-05 12:01:43.750  3666  3666 W PrefCtrlListHelper: Cannot instantiate controller from reflection: com.android.settings.notification.ImportanceResetPreferenceController
02-05 12:01:43.750  3666  3666 D PrefCtrlListHelper: Could not find Context-only controller for pref: com.android.settings.location.LocationIndicatorsPreferenceController
02-05 12:01:43.750  3666  3666 W PrefCtrlListHelper: Cannot instantiate controller from reflection: com.android.settings.location.LocationIndicatorsPreferenceController
02-05 12:01:43.759   469   484 E UserRestrictionsUtils: Unknown restriction queried by uid 1001000 (com.android.providers.settings et al): null
02-05 12:01:43.761   469   484 E UserRestrictionsUtils: Unknown restriction queried by uid 1001000 (com.android.providers.settings et al): null
02-05 12:01:43.764   469   893 E UserRestrictionsUtils: Unknown restriction queried by uid 1001000 (com.android.providers.settings et al): null
02-05 12:01:43.766   469   893 E UserRestrictionsUtils: Unknown restriction queried by uid 1001000 (com.android.providers.settings et al): null
02-05 12:01:43.769   469   893 E UserRestrictionsUtils: Unknown restriction queried by uid 1001000 (com.android.providers.settings et al): null
02-05 12:01:43.773   469   893 E UserRestrictionsUtils: Unknown restriction queried by uid 1001000 (com.android.providers.settings et al): null
02-05 12:01:43.787   469   893 E UserRestrictionsUtils: Unknown restriction queried by uid 1001000 (com.android.providers.settings et al): null
02-05 12:01:43.807   150   150 I servicemanager: Could not find android.hardware.dumpstate.IDumpstateDevice/default in the VINTF manifest.
02-05 12:01:43.809   151   151 I hwservicemanager: getTransport: Cannot find entry android.hardware.dumpstate@1.1::IDumpstateDevice/default in either framework or device VINTF manifest.
02-05 12:01:43.811   151   151 I hwservicemanager: getTransport: Cannot find entry android.hardware.dumpstate@1.0::IDumpstateDevice/default in either framework or device VINTF manifest.
02-05 12:01:43.823  3666  3666 I eveloperoptions: type=1400 audit(0.0:118): avc: denied { read } for name="pagetypeinfo" dev="proc" ino=4026531859 scontext=u:r:system_app:s0 tcontext=u:object_r:proc_pagetypeinfo:s0 tclass=file permissive=1
02-05 12:01:43.869  3666  3666 W ProcStatsManager: No process com.android.dynsystem:dynsystem/1000 for service com.android.dynsystem.DynamicSystemInstallationService
02-05 12:01:43.869  3666  3666 W ProcStatsManager: No process com.android.providers.calendar/10017 for service com.android.providers.calendar.CalendarProviderJobService
02-05 12:01:43.869  3666  3666 W ProcStatsManager: No process com.android.providers.calendar/1010017 for service com.android.providers.calendar.CalendarProviderJobService
02-05 12:01:43.869  3666  3666 W ProcStatsManager: No process com.android.keychain/1000 for service com.android.keychain.KeyChainService
02-05 12:01:43.870  3666  3666 W ProcStatsManager: No process com.android.keychain/1001000 for service com.android.keychain.KeyChainService
02-05 12:01:43.870  3666  3666 W ProcStatsManager: No process com.android.gallery3d/10078 for service com.android.gallery3d.app.PackagesMonitor$AsyncService
02-05 12:01:43.870  3666  3666 W ProcStatsManager: No process com.android.gallery3d/1010078 for service com.android.gallery3d.app.PackagesMonitor$AsyncService
02-05 12:01:43.870  3666  3666 W ProcStatsManager: No process android.ext.services/1110102 for service android.ext.services.autofill.InlineSuggestionRenderServiceImpl
02-05 12:01:43.870  3666  3666 W ProcStatsManager: No process android.ext.services/1210102 for service android.ext.services.autofill.InlineSuggestionRenderServiceImpl
02-05 12:01:43.870  3666  3666 W ProcStatsManager: No process android.car.usb.handler/10042 for service android.car.usb.handler.BootUsbService
02-05 12:01:43.870  3666  3666 W ProcStatsManager: No process com.android.providers.media.module/1110101 for service com.android.providers.media.fuse.ExternalStorageServiceImpl
02-05 12:01:43.871  3666  3666 W ProcStatsManager: No process com.android.providers.media.module/1210101 for service com.android.providers.media.fuse.ExternalStorageServiceImpl
02-05 12:01:43.871  3666  3666 W ProcStatsManager: No process com.android.providers.media.module/1210101 for service com.android.providers.media.MediaService
02-05 12:01:43.871  3666  3666 W ProcStatsManager: No process com.android.permissioncontroller/1210099 for service com.android.permissioncontroller.permission.service.PermissionControllerServiceImpl
02-05 12:01:43.871  3666  3666 W ProcStatsManager: No process com.android.permissioncontroller/1210099 for service com.android.permissioncontroller.role.service.RoleControllerServiceImpl
02-05 12:01:43.871  3666  3666 W ProcStatsManager: No process com.android.bluetooth/1001002 for service com.android.bluetooth.btservice.AdapterService
02-05 12:01:43.823  3666  3666 I eveloperoptions: type=1400 audit(0.0:119): avc: denied { open } for path="/proc/pagetypeinfo" dev="proc" ino=4026531859 scontext=u:r:system_app:s0 tcontext=u:object_r:proc_pagetypeinfo:s0 tclass=file permissive=1
02-05 12:01:43.823  3666  3666 I eveloperoptions: type=1400 audit(0.0:120): avc: denied { getattr } for path="/proc/pagetypeinfo" dev="proc" ino=4026531859 scontext=u:r:system_app:s0 tcontext=u:object_r:proc_pagetypeinfo:s0 tclass=file permissive=1
02-05 12:01:43.925  3666  3666 D DevSettingsDashboard: All preferences added, reporting fully drawn
02-05 12:01:43.933   469   491 W WindowManager: lockNow pending, ignore updating lockscreen timeout
02-05 12:01:43.938   469   893 D CompatibilityChangeReporter: Compat change id reported: 161145287; UID 1001000; state: DISABLED
02-05 12:01:43.942   469   491 W WindowManager: lockNow pending, ignore updating lockscreen timeout
02-05 12:01:43.945  3666  3666 D SettingsActivity: Executed frag manager pendingTransactions
02-05 12:01:43.947   283   412 W TransactionTracing: Could not find layer handle 0xb400007a380d57b0
02-05 12:01:43.949  3666  3666 D AndroidRuntime: Shutting down VM
02-05 12:01:43.950   469   491 W WindowManager: lockNow pending, ignore updating lockscreen timeout
02-05 12:01:43.951  3666  3666 E AndroidRuntime: FATAL EXCEPTION: main
02-05 12:01:43.951  3666  3666 E AndroidRuntime: Process: com.android.car.developeroptions, PID: 3666
02-05 12:01:43.951  3666  3666 E AndroidRuntime: java.lang.IncompatibleClassChangeError: Class 'androidx.window.embedding.EmbeddingAdapter$$ExternalSyntheticLambda2' does not implement interface 'androidx.window.extensions.core.util.function.Predicate' in call to 'boolean androidx.window.extensions.core.util.function.Predicate.test(java.lang.Object)' (declaration of 'androidx.window.extensions.embedding.ActivityRule' appears in /system/system_ext/framework/androidx.window.extensions.jar)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at androidx.window.extensions.embedding.ActivityRule.matchesActivity(ActivityRule.java:57)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at androidx.window.extensions.embedding.SplitController.shouldExpand(SplitController.java:1836)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at androidx.window.extensions.embedding.SplitController.resolveActivityToContainer(SplitController.java:717)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at androidx.window.extensions.embedding.SplitController.onActivityCreated(SplitController.java:670)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at androidx.window.extensions.embedding.SplitController$LifecycleCallbacks.onActivityPostCreated(SplitController.java:1950)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at android.app.Application.dispatchActivityPostCreated(Application.java:380)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at android.app.Activity.dispatchActivityPostCreated(Activity.java:1395)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8352)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8321)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3625)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7918)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-05 12:01:43.951  3666  3666 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
02-05 12:01:43.952  1384  1423 D OpenGLRenderer: endAllActiveAnimators on 0xb400007627c4b720 (StateListDrawable) with handle 0xb400007537c22b90
02-05 12:01:43.952  1384  1423 D OpenGLRenderer: endAllActiveAnimators on 0xb400007627cb13d0 (StateListDrawable) with handle 0xb400007537c3b7c0
02-05 12:01:43.953   469   484 W WindowManager: lockNow pending, ignore updating lockscreen timeout
02-05 12:01:43.958   469   893 W ActivityTaskManager:   Force finishing activity com.android.car.developeroptions/.CarDevelopmentSettingsDashboardActivity
02-05 12:01:43.958   469  3693 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
02-05 12:01:43.983   469   893 W WindowManager: lockNow pending, ignore updating lockscreen timeout
02-05 12:01:43.986   469   893 W ActivityTaskManager:   Force finishing activity com.android.car.settings/.common.SubSettingsActivity
02-05 12:01:43.989   469   893 W WindowManager: lockNow pending, ignore updating lockscreen timeout
02-05 12:01:43.993  3666  3666 I Process : Sending signal. PID: 3666 SIG: 9
02-05 12:01:44.028   469  3632 I ActivityManager: Process com.android.car.developeroptions (pid 3666) has died: fg  TOP
02-05 12:01:44.028   469   498 I libprocessgroup: Successfully killed process cgroup uid 1001000 pid 3666 in 0ms
02-05 12:01:44.031   254   254 I Zygote  : Process 3666 exited due to signal 9 (Killed)
```

**Comment by KonstaT** [comment]
Closing old AOSP13 related issues as we're currently at Android 15.

Opening developer options works on Android Automotive builds from both `android-14.0.0_r67` and `android-15.0.0_r1` branches.

**Comment by MagicAndre1981** [comment]
> Opening developer options works on Android Automotive builds from both `android-14.0.0_r67` and `android-15.0.0_r1` branches.

for me it fails on Android TV 15 with android-15.0.0_r2. Compile for RPi4 works fine, [USB boot works after changing the fstab entries](https://github.com/raspberry-vanilla/android_local_manifest/wiki/USB-boot), enabling Developer Settings works, but when I tried to open developer settings to enable adb (over network) it closes.
