### ISSUE TITLE
SMS not working on AOSP13 Android Automotive

### ISSUE THREAD

**Issue by p147123456** [raspberry-vanilla/android_local_manifest#82]
AAOS default application com.android.car.messenger
doesn't work error code:
 
 com.android.car.messenger            E  FATAL EXCEPTION: main
                                                                                                    Process: com.android.car.messenger, PID: 7350
                                                                                                    java.lang.SecurityException: Failed to find provider mms-sms for user 10; expected to find a valid ContentProvider for this authority
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2995)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2978)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2920)
                                                                                                    	at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:1032)
                                                                                                    	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2712)
                                                                                                    	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2660)
                                                                                                    	at com.android.car.messenger.impl.datamodels.ContentProviderLiveData.onActive(ContentProviderLiveData.java:58)
                                                                                                    	at com.android.car.messenger.impl.datamodels.NewMessageLiveData.onActive(NewMessageLiveData.java:82)
                                                                                                    	at androidx.lifecycle.LiveData.changeActiveCounter(LiveData.java:390)
                                                                                                    	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:466)
                                                                                                    	at androidx.lifecycle.LiveData.observeForever(LiveData.java:234)
                                                                                                    	at com.android.car.messenger.core.service.MessengerService.subscribeToNotificationUpdates(MessengerService.java:97)
                                                                                                    	at com.android.car.messenger.core.service.MessengerService.$r8$lambda$GNhp1kllAwdq_0IRrKAIVSWonbM(Unknown Source:0)
                                                                                                    	at com.android.car.messenger.core.service.MessengerService$$ExternalSyntheticLambda2.run(Unknown Source:2)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.content.ContentService.registerContentObserver(ContentService.java:376)
                                                                                                    	at android.content.IContentService$Stub.onTransact(IContentService.java:486)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1280)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1244)

**Comment by KonstaT** [comment]
Closing old AOSP13 related issues as we're currently at Android 15.
